USE [master]
GO

/****** Object:  Database [iList]    Script Date: 9/17/2017 10:51:39 PM ******/
CREATE DATABASE [iList]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CRUD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\CRUD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CRUD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\CRUD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [iList] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [iList].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [iList] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [iList] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [iList] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [iList] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [iList] SET ARITHABORT OFF 
GO

ALTER DATABASE [iList] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [iList] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [iList] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [iList] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [iList] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [iList] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [iList] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [iList] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [iList] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [iList] SET  DISABLE_BROKER 
GO

ALTER DATABASE [iList] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [iList] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [iList] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [iList] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [iList] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [iList] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [iList] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [iList] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [iList] SET  MULTI_USER 
GO

ALTER DATABASE [iList] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [iList] SET DB_CHAINING OFF 
GO

ALTER DATABASE [iList] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [iList] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [iList] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [iList] SET QUERY_STORE = OFF
GO

USE [iList]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [iList] SET  READ_WRITE 
GO


